// src/components/AppHeader.vue

<template>
  <header class="bg-white border-b px-4 py-3 flex justify-between items-center">
    <div class="flex items-center">
      <Menu :size="20" class="text-gray-700 mr-3" />
      <h1 class="font-medium">Доставка</h1>
    </div>
    <div class="flex items-center gap-3">
      <div class="flex items-center">
        <div class="h-2 w-2 rounded-full bg-green-500 mr-2"></div>
        <span class="text-sm">В сети</span>
      </div>
      <Avatar class="h-8 w-8">
        <AvatarImage src="/placeholder.svg" />
        <AvatarFallback>КС</AvatarFallback>
      </Avatar>
    </div>
  </header>
</template>

<script setup lang="ts">
import { Menu } from 'lucide-vue-next'
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar'
</script>

// src/components/AppHeader.tsx
import React from 'react';
import { Button } from '@/components/ui/button';
import { BellRing, Menu } from 'lucide-react';

export const AppHeader: React.FC = () => {
  return (
    <header className="flex items-center justify-between p-4 border-b bg-card">
      <Button variant="outline" size="icon">
        <Menu size={20} />
      </Button>
      
      <div className="flex items-center">
        <div className="h-2 w-2 bg-green-500 rounded-full mr-2"></div>
        <span className="font-medium">На смене</span>
      </div>
      
      <Button variant="outline" size="icon" className="relative">
        <BellRing size={20} />
        <span className="absolute -top-1 -right-1 h-4 w-4 bg-primary text-xs text-primary-foreground rounded-full flex items-center justify-center">
          2
        </span>
      </Button>
    </header>
  );
};
